---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  labels:
    app: webapp
spec:
  storageClassName:  nfs-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

