---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80

